# Generated by Django 6.0.6 on 2026-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardaction',
            name='recurrence_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hazardaction',
            name='result_detail',
            field=models.TextField(blank=True),
        ),
    ]
